import { Cormorant_Garamond, Poppins } from "next/font/google";
import "./globals.css";
import SmoothScrolling from "./utils/SmoothScrolling";
import Header from "./components/Header";

// Cormorant Garamond (for headings)
const cormorantGaramond = Cormorant_Garamond({
  variable: "--font-cormorant",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

// Poppins (for body text / UI)
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["200","300","400", "500", "600", "700"],
  display: "swap",
});

export const metadata = {
  title: "Friigoo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${cormorantGaramond.variable} ${poppins.variable} antialiased`}
      >
        <Header />
        <SmoothScrolling>{children}</SmoothScrolling>
      </body>
    </html>
  );
}
