import { Cormorant_Garamond, Poppins } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import SmoothScrolling from "./utils/SmoothScrolling";
import Header from "./components/Header";
import Footer from "./components/Footer";

// Cormorant Garamond (for headings)
const cormorantGaramond = Cormorant_Garamond({
  variable: "--font-cormorant",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const bauhaus = localFont({
  src: [
    {
      path: "./bauhaus-font/BauhausStd-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./bauhaus-font/BauhausStd-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./bauhaus-font/BauhausStd-Demi.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "./bauhaus-font/BauhausStd-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "./bauhaus-font/BauhausStd-Heavy.woff2",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-bauhaus",
  display: "swap",
});

// Poppins (for body text / UI)
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
  display: "swap",
});

export const metadata = {
  title: "Friigoo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${cormorantGaramond.variable} ${poppins.variable} ${bauhaus.variable} antialiased`}
      >
        <SmoothScrolling>
          <Header />
          <div className="">
            {children}
          </div>
          <Footer />
        </SmoothScrolling>
      </body>
    </html>
  );
}
